### ISSUE TITLE
May I use the name "updock" for my program?

### ISSUE THREAD

**Issue by Y0hy0h** [stephencroberts/updock#1]
I am currently writing a tool for detecting updates to Dockerfiles whose working title is [updock](https://github.com/Y0hy0h/updock). It does something different than your tool, but is also related to Docker.

I wanted to check with you whether you'd like to keep the name for this project, or else if it's ok that I use it for mine?

**Comment by stephencroberts** [comment]
Hi, @Y0hy0h, I really appreciate you reaching out to me. I do plan to keep the name `undock` and have some future plans in the works as well for this project.

**Comment by Y0hy0h** [comment]
Ok, then I'll rename my project! Thanks for responding so quickly!
